apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: smithjunior/gitopsfc
  newTag: a94980edffd21e0954a4d3817990edc6ba94edfd
